[project]
authors = ["carschandler <92899389+carschandler@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ece595rl"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.1.1,<3"
ipython = ">=8.27.0,<9"
matplotlib = ">=3.9.2,<4"
plotly = ">=5.24.0,<6"
python-kaleido = ">=0.2.1,<0.3"
jupyter = ">=1.1.1,<2"
pandas = ">=2.2.2,<3"
jupytext = ">=1.16.4,<2"
